version: '3.8'
services:
  db:
    image: postgres:15
    container_name: idea_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: ideaboard
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: idea_backend
    restart: unless-stopped
    command: sh -c "node scripts/migrate.js && node src/index.js"
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@db:5432/ideaboard
      PORT: 4000
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./migrations:/usr/src/app/migrations:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: idea_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
      NODE_ENV: production
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:


